#!/usr/bin/env bash
set -euo pipefail
export DOCKER_API_VERSION=1.43

# Timestamp function for logging
log_with_timestamp() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

# Base tools for Oh My Zsh and kind
sudo apt-get update
sudo apt-get install -y --no-install-recommends zsh git curl wget ca-certificates

# Node.js 24.x (LTS)
if ! command -v node >/dev/null 2>&1 || ! node --version | grep -q "^v24\."; then
  log_with_timestamp "Installing Node.js 24.x..."
  curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi

# yarn (latest stable)
if ! command -v yarn >/dev/null 2>&1; then
  log_with_timestamp "Installing yarn..."
  sudo npm install -g yarn
fi

# Oh My Zsh (unattended)
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Powerlevel10k theme for Oh My Zsh
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  log_with_timestamp "Installing Powerlevel10k theme..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  
  # Set theme in .zshrc
  if [ -f "$HOME/.zshrc" ]; then
    sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$HOME/.zshrc"
  fi
  
  # Create a default p10k config to skip the configuration wizard
  # This uses the "rainbow" style with colorful segments and two-line prompt
  if [ ! -f "$HOME/.p10k.zsh" ]; then
    cat > "$HOME/.p10k.zsh" <<'P10K_EOF'
# Generated by Powerlevel10k configuration wizard on $(date)
# Based on the "rainbow" style with two-line prompt for development containers

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # Prompt style: rainbow
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # Basic style - Rainbow uses colored backgrounds
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'

  # Prompt segments - Two lines with newline before prompt_char
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    newline
    prompt_char
  )
  
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    virtualenv
    pyenv
    goenv
    nodenv
    nvm
    nodeenv
    rbenv
    kubecontext
    terraform
    aws
    azure
    gcloud
    context
    time
  )

  # OS icon colors (rainbow style)
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

  # Directory colors (rainbow style - blue)
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=232
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=4

  # Git/VCS colors (rainbow style - green)
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=232
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=232
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=3
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=232
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3

  # Prompt char colors
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=

  # Status colors
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=232
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=2
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=232
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1

  # Command execution time colors (rainbow style - yellow)
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=232
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3

  # Kubernetes context colors (rainbow style - cyan)
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kustomize'
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=232
  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=6

  # Virtualenv colors (rainbow style - blue)
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=232
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=4

  # Time colors (rainbow style - magenta)
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=232
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=5

  # Git settings
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Transient prompt
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # Instant prompt mode
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false
}

# Restore options.
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
P10K_EOF
  fi
  
  # Source p10k config in .zshrc if not already done
  if [ -f "$HOME/.zshrc" ] && ! grep -q "source ~/.p10k.zsh" "$HOME/.zshrc"; then
    echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> "$HOME/.zshrc"
  fi
  
  log_with_timestamp "Powerlevel10k installed! Note: For best experience, install 'MesloLGS NF' font on your local machine."
  log_with_timestamp "Download from: https://github.com/romkatv/powerlevel10k#manual-font-installation"
fi

# kind (latest release)
if ! command -v kind >/dev/null 2>&1; then
  curl -fsSL https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64 -o /tmp/kind
  chmod +x /tmp/kind
  sudo mv /tmp/kind /usr/local/bin/kind
fi

# kubectl (latest stable)
if ! command -v kubectl >/dev/null 2>&1; then
  KUBECTL_VERSION="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
  curl -fsSL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /tmp/kubectl
  chmod +x /tmp/kubectl
  sudo mv /tmp/kubectl /usr/local/bin/kubectl
fi

# helm (latest stable)
if ! command -v helm >/dev/null 2>&1; then
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi

# Ensure helm is executable (fix permissions if needed)
if [ -f /usr/local/bin/helm ]; then
  sudo chmod +x /usr/local/bin/helm
fi

# Add kubectl alias to zsh config
if [ -f "$HOME/.zshrc" ] && ! grep -q "^alias k='kubectl'$" "$HOME/.zshrc"; then
  echo "alias k='kubectl'" >> "$HOME/.zshrc"
fi

# Set Docker API version to match host daemon
if [ -f "$HOME/.zshrc" ] && ! grep -q "^export DOCKER_API_VERSION=" "$HOME/.zshrc"; then
  echo "export DOCKER_API_VERSION=1.43" >> "$HOME/.zshrc"
fi

# Enable kubectl autocompletion for zsh (including alias k)
if [ -f "$HOME/.zshrc" ] && ! grep -q "kubectl completion zsh" "$HOME/.zshrc"; then
  cat >> "$HOME/.zshrc" <<'EOF'
source <(kubectl completion zsh)
compdef __start_kubectl k
EOF
fi

# Create a default kind cluster if Docker is available and no cluster exists
# if command -v docker >/dev/null 2>&1; then
#   if ! kind get clusters >/dev/null 2>&1 || ! kind get clusters | grep -q '^kind$'; then
#     kind create cluster --config kind.yaml
#   fi
# fi

